org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21

minecraft_version_range=[1.21,1.21.1)

neo_version=21.1.186

neo_version_range=[21.0.42-beta,)

loader_version_range=[4,)

atlas_version_range=[1.21.0-1.1.14,)

## Mod Properties

mod_id=hordes
mod_name=The-Hordes-1.21
mod_license=GNU LESSER GENERAL PUBLIC LICENSE Version 2.1
mod_version=1.6.3a
mod_authors=smileycorp
mod_group_id=net.smileycorp.hordes
mod_description=Adds mob horde invasions and zombie infections to the game.